"""Current-bank statistics, spectral queries, and signed pooling."""

from ember.ecp.bank_conditioning.anchor import (
    AnchorProgramState,
    NativeCandidateEncoder,
    ProgramNativeAnchorScorer,
)
from ember.ecp.bank_conditioning.operator import (
    BankConditioningError,
    BankStatistics,
    SpectralBankQuery,
    StreamingBankStatistics,
    StreamingSignedPool,
    batched_spectral_bank_query,
    bounded_relative_group_gain,
    materialized_bank_statistics,
    materialized_signed_pool,
    spectral_bank_query,
)
from ember.ecp.bank_conditioning.primal_dual import (
    NativeCovarianceStatistics,
    SpectralNativeCovariance,
    StreamingNativeCovariance,
    batched_spectral_native_covariances,
    native_candidate_mass,
)
from ember.ecp.bank_conditioning.program_primal import (
    PrimalProgramState,
    ProgramNativePrimalScorer,
)
from ember.ecp.bank_conditioning.functional_polar import (
    FunctionalBankStatistics,
    FunctionalPolarQueries,
    StreamingCenteredAnchor,
    StreamingFunctionalBankStatistics,
    batched_functional_polar_queries,
    bound_functional_queries,
    functional_polar_queries,
    normalize_replay_queries,
)
from ember.ecp.bank_conditioning.functional_sketch import (
    BankAdaptiveBasis,
    FunctionalTargetQueries,
    SketchCrossImage,
    SketchedFunctionalStatistics,
    StreamingProjectedFunctionalStatistics,
    StreamingSketchCrossImage,
    bank_adaptive_basis,
    fixed_nested_projection,
    functional_target_queries,
)
from ember.ecp.bank_conditioning.whitening import (
    FeatureStatistics,
    FeatureWhitener,
    FeatureWhiteningPlan,
    StreamingFeatureStatistics,
    batched_feature_whiteners,
    build_feature_whitening_plan,
    identity_feature_whitening_plan,
)
from ember.ecp.bank_conditioning.set_summary import (
    SetConditionedScalarEnergy,
    SetSummaryFactorSelector,
    SetSummaryStatistics,
    StreamingSetMoments,
    StreamingSetSignedPool,
    TaskLocalSelectionCode,
    materialized_set_signed_pool,
)

__all__ = [
    "AnchorProgramState",
    "BankAdaptiveBasis",
    "BankConditioningError",
    "BankStatistics",
    "FunctionalBankStatistics",
    "FunctionalPolarQueries",
    "FunctionalTargetQueries",
    "FeatureStatistics",
    "FeatureWhitener",
    "FeatureWhiteningPlan",
    "NativeCandidateEncoder",
    "NativeCovarianceStatistics",
    "PrimalProgramState",
    "ProgramNativePrimalScorer",
    "ProgramNativeAnchorScorer",
    "SketchCrossImage",
    "SetConditionedScalarEnergy",
    "SetSummaryFactorSelector",
    "SetSummaryStatistics",
    "SketchedFunctionalStatistics",
    "SpectralBankQuery",
    "StreamingBankStatistics",
    "StreamingNativeCovariance",
    "StreamingCenteredAnchor",
    "StreamingFunctionalBankStatistics",
    "StreamingProjectedFunctionalStatistics",
    "StreamingSketchCrossImage",
    "StreamingFeatureStatistics",
    "StreamingSignedPool",
    "StreamingSetMoments",
    "StreamingSetSignedPool",
    "TaskLocalSelectionCode",
    "SpectralNativeCovariance",
    "batched_spectral_bank_query",
    "batched_spectral_native_covariances",
    "bank_adaptive_basis",
    "batched_feature_whiteners",
    "batched_functional_polar_queries",
    "bound_functional_queries",
    "build_feature_whitening_plan",
    "bounded_relative_group_gain",
    "materialized_bank_statistics",
    "materialized_signed_pool",
    "materialized_set_signed_pool",
    "native_candidate_mass",
    "functional_polar_queries",
    "fixed_nested_projection",
    "functional_target_queries",
    "identity_feature_whitening_plan",
    "normalize_replay_queries",
    "spectral_bank_query",
]
